### PR TITLE
Improved info buttons

### LINKED ISSUE #6: Are the information buttons needed?
@grzesiek2010 The button names are clear enough that I'm not really feeling like the information buttons add much.

What about including the code instead? I mean something like
```
Intent i = new Intent(Intent.ACTION_VIEW);
i.setType("vnd.android.cursor.dir/vnd.odk.form");
```

That seems it would be more useful! @yanokwa what do you think?

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel 
Let me know what you think.

**Comment by lognaturel** [comment]
On my devices the code looks very tiny and the scrolling doesn't work!

Since the first 4 buttons have the same name as in Collect, I think their meaning is very clear. I propose only including the code in the information buttons. And I think a check for accuracy would be helpful -- I notice that there's a quote missing in the first one!

For the last two, they actually show two things -- getting a list of forms/instances and opening a specific form/instance. How about something like "Get a list of forms/instances from Collect. Specific forms/instances can be launched using their ID."

@mmarciniak90 would like to get your opinion on this too!

**Comment by grzesiek2010** [comment]
@lognaturel fixed.

**Comment by mmarciniak90** [comment]
@lognaturel I agree, this app is addressed to developers so it is good idea to inform about part of code.

I noticed that text size is reduced on 2 devices.
I just want to inform about this case, I think it is not worth to work on fix.
Text is readable and it happens only on devices with Android v4.1 and v4.2.
Use case : 
1. User opens collectTester app in vertical position
2. User changes device orientation to horizontal
3. User clicks on some info button and closes message
4. User changes device orientation to vertical
5. User clicks on some info button
6. Dialog with code appears but text size is reduced. 
screenshot_2017-10-23-14-33-55
Before:
screenshot_2017-10-23-14-33-41

I did not notice other cases. 
I tested also on Android 4.4, 5.1, 6.0, 7.0.
Scroll is available. 
screenshot_20171023-145834

**Comment by grzesiek2010** [comment]
Smaller but still legible and the case it's not really common so I think we can merge it. Do you agree with me? @lognaturel

**Comment by lognaturel** [comment]
Yes, thank you @grzesiek2010 @mmarciniak90. Please merge!

**Pull request merged**
