### PR TITLE
Form download intent

### LINKED ISSUE #18: Add form download intent test
This demonstrates how this [PR](https://github.com/opendatakit/collect/pull/2348) from [this issue](https://github.com/opendatakit/collect/issues/2339) works. See more in the above links.

### IMPLEMENTATION

The tester should be able to select the download form on the main page. The user will be taken to another page where they can enter the form_id of the form they want to download.  Above the *download button* will be status text with the formID and current status if any.

### PR DESCRIPTION
**Pull request by ekigamba**
fixes #18

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@ekigamba I noticed that status changes to the default when I change device orientation

**Comment by grzesiek2010** [comment]
@ekigamba There is also a wrong message after clicking on an info button next to the "Download Form" button.

**Comment by ekigamba** [comment]
> @ekigamba There is also a wrong message after clicking on an info button next to the "Download Form" button.

I will look at this @grzesiek2010

**Comment by ekigamba** [comment]
> @ekigamba I noticed that status changes to the default when I change device orientation

I will fix this @mmarciniak90

**Comment by ekigamba** [comment]
This is blocked for now due to new changes to the external app form-download-request feature

**Comment by grzesiek2010** [comment]
@ekigamba 

is it still blocked or ready? If it's ready could you resolve conflicts?

**Comment by ekigamba** [comment]
@grzesiek2010 Cool, I'll look at it

**Comment by lognaturel** [comment]
@grzesiek2010 Could you please see about resolving the conflicts? You should be able to push into this branch. I think it would be good to get something merged and iterate on it if needed.

**Comment by kkrawczyk123** [comment]
I have no idea why I haven't noticed that before. But the new view is displayed only when the storage permissions are turned off, when they are on - the old view is displayed. There is one condition for that there must be present at least one submission filled but not sent before.  An issue doesn't occur when I try to resent old submission by input its id. I am attaching a gif of the scenario:
ezgif com-video-to-gif

**Comment by grzesiek2010** [comment]
@ekigamba 
are you going finish work on this and fix the issue pointed by @kkrawczyk123 ?

**Comment by ekigamba** [comment]
@grzesiek2010 Yes, I will look at it and fix it.  Sorry, I forgot about it

**Comment by grzesiek2010** [comment]
Fixed in #27

**Pull request closed without merging**
